apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
  - name: k8s-infra
    type: core.Directory
    children:
      - name: xlr
        type: openshift.Server
        serverUrl: https://api.acierto.lnfl.p1.openshiftapps.com:6443
        openshiftToken: sha256~TxxXE5EiBcaChRXd0_cJeWSNmiE58O3itEI3KA-Xtq0
        verifyCertificates: false
        children:
          - name: default
            type: openshift.Project
            projectName: default
