apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xlr-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xlr-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: digitalai
