apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
  - name: k8s-infra
    type: core.Directory
    children:
    - name: xlr
      type: k8s.Master
      apiServerURL: < Update using server info from the kubeconfig file >
      skipTLS: true
      debug: true
      caCert: |-
        -----BEGIN CERTIFICATE-----

        -----END CERTIFICATE-----
      tlsCert: |-
        -----BEGIN CERTIFICATE-----

        -----END CERTIFICATE-----
      tlsPrivateKey: |-
        -----BEGIN RSA PRIVATE KEY-----
        
        -----END RSA PRIVATE KEY-----
      children:
        - name: digitalai
          type: k8s.Namespace
          namespaceName: digitalai
