apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
  - name: k8s-infra
    type: core.Directory
    children:
    - name: xlr
      type: k8s.Master
      apiServerURL: < Update using server info from the kubeconfig file>
      skipTLS: true
      debug: true
      caCert: |-
        <certificate-authority-data in base64 decoded>
        -----BEGIN CERTIFICATE-----
        
        -----END CERTIFICATE-----
      isEKS: true
      useGlobal: true
      regionName: <Update using  region info from the kubeconfig file>
      clusterName: <Update using cluster-name field from the kubeconfig file>
      accessKey: <Update the AWS accessKey details>
      accessSecret: <Update the AWS accessSecret details>
      isAssumeRole: <Set to true for assumeRole based access to the cluster>
      # If 'isAssumeRole' set to 'true', uncomment the following lines and provide the values.
      # accountId: <Update the AWS account ID>
      # roleName: <Update the AWS role name>
      # roleArn: <Update the AWS roleArn for the IAM role>
      # durationSeconds: <Update the duration in seconds of the role session.(900 to max session duration)>
      # sessionToken: <Update the session token of the AWS temporary credentials>
      # End of "isAssumeRole" property related fields
      children:
        - name: digitalai
          type: k8s.Namespace
          namespaceName: digitalai
