env1 = repository.create(factory.configurationItem('Environments/repo-by-name-an-env1','udm.Environment'))
env2 = repository.create(factory.configurationItem('Environments/repo-by-name-an-env2','udm.Environment'))
env3 = repository.create(factory.configurationItem('Environments/repo-by-name-an-env%','udm.Environment'))
env4 = repository.create(factory.configurationItem('Environments/repo-by-name-an%env%','udm.Environment'))

envsResult = repository.searchByName('repo-by-name-an-env1')
assertTrue(env1.id in envsResult)
assertTrue(env2.id not in envsResult)
assertTrue(env3.id not in envsResult)
assertTrue(env4.id not in envsResult)

envsResult2 = repository.searchByName('repo-by-name-an-env%')
assertTrue(env1.id in envsResult2)
assertTrue(env2.id in envsResult2)
assertTrue(env3.id in envsResult2)
assertTrue(env4.id not in envsResult2)

envsResult3 = repository.searchByName('repo-by-name-an%env%')
assertTrue(env1.id in envsResult3)
assertTrue(env2.id in envsResult3)
assertTrue(env3.id in envsResult3)
assertTrue(env4.id in envsResult3)

envsResult4 = repository.searchByName('repo-by-name-an%env2')
assertTrue(env1.id not in envsResult4)
assertTrue(env2.id in envsResult4)
assertTrue(env3.id not in envsResult4)
assertTrue(env4.id not in envsResult4)

envsResult5 = repository.searchByName('repo-by-name-an\%env%')
assertTrue(env1.id not in envsResult5)
assertTrue(env2.id not in envsResult5)
assertTrue(env3.id not in envsResult5)
assertTrue(env4.id in envsResult5)

envsResult6 = repository.searchByName('repo-by-name-an%env\%')
assertTrue(env1.id not in envsResult6)
assertTrue(env2.id not in envsResult6)
assertTrue(env3.id in envsResult6)
assertTrue(env4.id in envsResult6)

envsResult7 = repository.searchByName('repo-by-name-an\%env\%')
assertTrue(env1.id not in envsResult7)
assertTrue(env2.id not in envsResult7)
assertTrue(env3.id not in envsResult7)
assertTrue(env4.id in envsResult7)

envsResult8 = repository.searchByName('Repo-By-Name-AN\%env%')
assertTrue(env1.id not in envsResult8)
assertTrue(env2.id not in envsResult8)
assertTrue(env3.id not in envsResult8)
assertTrue(env4.id in envsResult8)

envsResult9 = repository.searchByName('Repo-By-Name-AN\%env\%')
assertTrue(env1.id not in envsResult9)
assertTrue(env2.id not in envsResult9)
assertTrue(env3.id not in envsResult9)
assertTrue(env4.id not in envsResult9)

repository.delete(env1.id)
repository.delete(env2.id)
repository.delete(env3.id)
repository.delete(env4.id)
